### ISSUE TITLE
Support `maxAge` option in stale-while-revalidate cache policy

### ISSUE THREAD

**Issue by JunlinPan-Crypto** [grischaerbe/cacheables#4]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-while-revalidate

Example:
```ts
// the cache is fresh for  1 hours (3600s). After 1 hours, it becomes stale but the cache is allowed to reuse it for any requests that are made in the following hours
// 'silently' update the cache will make the cache be fresh again
cache.cacheable(() => fetch(url), 'a', { 
  cachePolicy: 'stale-while-revalidate',
  maxAge: 60 * 60 * 1000,
})
```

**Comment by grischaerbe** [comment]
Interesting addition! I'm imagining the mechanics to be a little different. Considering your example and that there is a cached value:

```ts
cache.cacheable(() => fetch(url), 'a', { 
  cachePolicy: 'stale-while-revalidate',
  maxAge: 60 * 60 * 1000, // 1h
})
```

If the cache is younger than 1h, return the cached value without silently updating it.  
If the cache is older than 1h, return the cached value and silently update it.

Is that how you thought about it too?

**Comment by JunlinPan-Crypto** [comment]
@grischaerbe Yes, this will consist with HTTP `stale-while-revalidate` cache policy

**Comment by grischaerbe** [comment]
@JunlinPan-Crypto Feel free to give it a try :)

**Comment by JunlinPan-Crypto** [comment]
@grischaerbe You are so efficient!👍 I will have a try.
